"use strict";
// THIS FILE IS AUTOMATICALLY GENERATED. TO UPDATE THIS FILE YOU NEED TO CHANGE THE
// CORRESPONDING JSON SCHEMA FILE, THEN RUN devkit-admin build (or bazel build ...).
Object.defineProperty(exports, "__esModule", { value: true });
exports.Runner = exports.CodeCoverageReporterEnum = void 0;
var CodeCoverageReporterEnum;
(function (CodeCoverageReporterEnum) {
    CodeCoverageReporterEnum["Cobertura"] = "cobertura";
    CodeCoverageReporterEnum["Html"] = "html";
    CodeCoverageReporterEnum["Json"] = "json";
    CodeCoverageReporterEnum["JsonSummary"] = "json-summary";
    CodeCoverageReporterEnum["Lcov"] = "lcov";
    CodeCoverageReporterEnum["Lcovonly"] = "lcovonly";
    CodeCoverageReporterEnum["Text"] = "text";
    CodeCoverageReporterEnum["TextSummary"] = "text-summary";
})(CodeCoverageReporterEnum || (exports.CodeCoverageReporterEnum = CodeCoverageReporterEnum = {}));
/**
 * Specifies the test runner to use for test execution.
 */
var Runner;
(function (Runner) {
    Runner["Karma"] = "karma";
    Runner["Vitest"] = "vitest";
})(Runner || (exports.Runner = Runner = {}));
